apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: game1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: game1
  template:
    metadata:
      labels:
        app: game1
    spec:
        containers:
          - name: snakegame
            image: shoaibk7/myimg:$BUILD_NUMBER
            ports:
              - containerPort: 8080
      
